---
# A light-codegen config file to generate a single module petstore project with Maven build
version: 1.0.0
groupId: com.networknt
artifactId: light-config-server
rootPackage: com.networknt.configserver
supportClient: false