---
openapi: "3.0.0"
servers:
- description: "Light Config Server"
  url: "https://config.neworknt.com/config-server"
info:
  description: "Light Config Server API"
  version: "1.0.0"
  title: "Light Config Server API"
  contact:
    email: "santosh.aherkar@gmail.com"
tags:
- name: "config-server"
  description: "Operations available in config server"
paths:
  /configs/property/ref:
    get:
      tags:
      - "config-server"
      summary: "Get reference data to populate the dropdown for property"
      operationId: "getPropertyRef"
      description: "Get property reference data with query parameters"
  /configs/property/search:
    post:
      tags:
      - "config-server"
      summary: "Search property key and value pairs with module and optional scope."
      operationId: "postPropertySearch"
      description: "Search property key and value pairs based on module and scope."
      security:
      - portal_auth:
        - "portal.r"
  /configs/property:
    post:
      tags:
      - "config-server"
      summary: "Create configs property key."
      operationId: "postConfigsProperty"
      description: "Create configs property key."
      security:
      - portal_auth:
        - "portal.w"
    put:
      tags:
      - "config-server"
      summary: "Update configs property key definition."
      operationId: "putConfigsProperty"
      description: "Update configs property key defintion."
      security:
      - portal_auth:
        - "portal.w"
    delete:
      tags:
      - "config-server"
      summary: "Delete configs property key definition."
      operationId: "deleteConfigProperty"
      description: "Delete configs property key definition."
      security:
      - portal_auth:
        - "portal.w"
  /configs/global/ref:
    get:
      tags:
      - "config-server"
      summary: "Get reference data to populate the dropdown for global property"
      operationId: "getConfigsGlobalRef"
      description: "Get configs reference data with query parameters"
  /configs/global/search:
    post:
      tags:
      - "config-server"
      summary: "Search global property key and value pairs with module, project, projver\
        \ and env."
      operationId: "postGlobalSearch"
      description: "Search global property key and value pairs based on module, project,\
        \ projver and env."
      security:
      - portal_auth:
        - "portal.r"
  /configs/global:
    post:
      tags:
      - "config-server"
      summary: "Create global configs property key and value."
      operationId: "postConfigsGlobal"
      description: "Create global configs property key and value."
      security:
      - portal_auth:
        - "portal.w"
    put:
      tags:
      - "config-server"
      summary: "Update global configs property key and value."
      operationId: "putConfigsGlobalProperty"
      description: "Update global configs property key and value."
      security:
      - portal_auth:
        - "portal.w"
    delete:
      tags:
      - "config-server"
      summary: "Delete global configs property key and value."
      operationId: "deleteConfigGlobalProperty"
      description: "Delete global configs property key and value."
      security:
      - portal_auth:
        - "portal.w"
  /configs/service/ref:
    get:
      tags:
      - "config-server"
      summary: "Get reference data to populate the dropdown for configs"
      operationId: "getConfigsServiceRef"
      description: "Get configs reference data with query parameters"
  /configs/service/search:
    post:
      tags:
      - "config-server"
      summary: "Search service entity with module and other parameters."
      operationId: "postConfigServiceSearch"
      description: "Search service entity based on module and other parameters."
      security:
      - portal_auth:
        - "portal.r"
  /configs/service:
    post:
      tags:
      - "config-server"
      summary: "Create a new service entity."
      operationId: "postConfigsService"
      description: "Create a new service entity."
      security:
      - portal_auth:
        - "portal.w"
    put:
      tags:
      - "config-server"
      summary: "Update an existing service entity."
      operationId: "putConfigsService"
      description: "Update a service entity."
      security:
      - portal_auth:
        - "portal.w"
    delete:
      tags:
      - "config-server"
      summary: "Delete an existing service entity and all the service properties."
      operationId: "deleteConfigService"
      description: "Delete a service entity along with properties."
      security:
      - portal_auth:
        - "portal.w"
  /configs/service/property:
    get:
      tags:
      - "config-server"
      summary: "Get all key/value pairs for a particular service"
      operationId: "getConfigsServiceProperty"
      description: "After clicking the detail button on the service list view, this\
        \ endpoint will get all the properties for the service"
      security:
      - portal_auth:
        - "portal.r"
    post:
      tags:
      - "config-server"
      summary: "Create a new service property."
      operationId: "postConfigsServiceProperty"
      description: "Create a new service property."
      security:
      - portal_auth:
        - "portal.w"
    put:
      tags:
      - "config-server"
      summary: "Update an existing service property."
      operationId: "putConfigsServiceProperty"
      description: "Update a service property."
      security:
      - portal_auth:
        - "portal.w"
    delete:
      tags:
      - "config-server"
      summary: "Delete an existing service property."
      operationId: "deleteConfigServiceProperty"
      description: "Delete a service property."
      security:
      - portal_auth:
        - "portal.w"
  /configs/{project}/{projver}/{service}/{servver}/{env}:
    get:
      tags:
      - "config-server"
      summary: "Get service configs for the specified project, project version, service,\
        \ service version and environment."
      operationId: "getServiceConfigs"
      description: "Get service configs for the specified project, project version,\
        \ service, service version and environment."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
  /certs/{project}/{projver}/{service}/{servver}/{env}:
    get:
      tags:
      - "config-server"
      summary: "Get certificates for the specified project, project version, service,\
        \ service version and environment."
      operationId: "getServiceCertificates"
      description: "Get certificates for the specified project, project version, service,\
        \ service version and environment. File content is returned as Base64 encoded."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
    post:
      tags:
      - "config-server"
      summary: "create config certificates for the specified project, project version,\
        \ service, service version and environment."
      operationId: "postServiceCertificates"
      description: "create config certificates for the specified project, project\
        \ version, service, service version and environment."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
    put:
      tags:
      - "config-server"
      summary: "update config certificates for the specified project, project version,\
        \ service, service version and environment."
      operationId: "putServiceCertificates"
      description: "update config certificates for the specified project, project\
        \ version, service, service version and environment."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
    delete:
      tags:
      - "config-server"
      summary: "Delete service certificates for the specified project, project version,\
        \ service, service version and environment."
      operationId: "deleteServiceCertificates"
      description: "Delete service certificates for the specified project, project\
        \ version, service, service version and environment."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
  /files/{project}/{projver}/{service}/{servver}/{env}:
    get:
      tags:
      - "config-server"
      summary: "Get config files for the specified project, project version, service,\
        \ service version and environment."
      operationId: "getServiceFiles"
      description: "Get config files for the specified project, project version, service,\
        \ service version and environment. File content is returned as Base64 encoded."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
    post:
      tags:
      - "config-server"
      summary: "create config files for the specified project, project version, service,\
        \ service version and environment."
      operationId: "postServiceFiles"
      description: "create config files for the specified project, project version,\
        \ service, service version and environment."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
    put:
      tags:
      - "config-server"
      summary: "update config files for the specified project, project version, service,\
        \ service version and environment."
      operationId: "putServiceFiles"
      description: "update config files for the specified project, project version,\
        \ service, service version and environment."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
    delete:
      tags:
      - "config-server"
      summary: "Delete service files for the specified project, project version, service,\
        \ service version and environment."
      operationId: "deleteServiceFiles"
      description: "Delete service files for the specified project, project version,\
        \ service, service version and environment."
      security:
      - portal_auth:
        - "A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2"
components:
  securitySchemes:
    portal_auth:
      type: "oauth2"
      flows:
        clientCredentials:
          tokenUrl: "https://lightapi.net/token"
          scopes:
            A8E73740C0041C03D67C3A951AA1D7533C8F9F2FB57D7BA107210B9BC9E06DA2: "default"
            portal.w: "write"
            portal.r: "read"