---
rootPackage: net.lightapi.portal.schema.command
handlerPackage: net.lightapi.portal.schema.command.handler
modelPackage: net.lightapi.portal.schema.command.model
artifactId: schema-command
groupId: net.lightapi
name: schema-command
version: 0.1.0
jsonPath: "/portal/command"
overwriteHandler: true
overwriteHandlerTest: true
httpPort: 8082
enableHttp: false
httpsPort: 8447
enableHttps: true
enableHttp2: true
enableRegistry: false
supportDb: false
supportH2ForTest: false
supportClient: false
kafkaProducer: true
kafkaConsumer: false
kafkaStreams: false
supportAvro: true
buildMaven: true
kafkaTopic: portal-event
