{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "OAuth2 Services Merged into a Monolithic App",
    "description": "OAuth2 Services with all endpoints in one API.",
    "contact": {
      "email": "stevehu@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "http://oauth2.networknt.com/"
    },
    {
      "url": "https://oauth2.networknt.com/"
    }
  ],
  "paths": {
    "/oauth2/client": {
      "post": {
        "description": "Return a client object",
        "operationId": "createClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.w"
            ]
          }
        ]
      },
      "put": {
        "description": "Return the updated client",
        "operationId": "updateClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Return all clients",
        "operationId": "getAllClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.r"
            ]
          }
        ]
      }
    },
    "/oauth2/client/{clientId}": {
      "delete": {
        "description": "Delete a client by Id",
        "operationId": "deleteClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a client by Id",
        "operationId": "getClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.r",
              "oauth.client.w"
            ]
          }
        ]
      }
    },
    "/oauth2/code": {
      "get": {
        "description": "Return 302 redirect with authorization code",
        "operationId": "getAuthCode"
      },
      "post": {
        "description": "Return 302 redirect with authorization code",
        "operationId": "postAuthCode"
      }
    },
    "/oauth2/key/{keyId}": {
      "get": {
        "description": "Get a key by Id",
        "operationId": "getKeyById",
        "security": [
          {
            "light_oauth2": [
              "oauth.key.r",
              "oauth.key.w"
            ]
          }
        ]
      }
    },
    "/oauth2/refresh_token": {
      "get": {
        "description": "Return all refresh tokens",
        "operationId": "getAllRefreshToken",
        "security": [
          {
            "light_oauth2": [
              "oauth.refresh_token.r"
            ]
          }
        ]
      }
    },
    "/oauth2/refresh_token/{refreshToken}": {
      "delete": {
        "description": "Delete a refresh token",
        "operationId": "deleteRefreshToken",
        "security": [
          {
            "light_oauth2": [
              "oauth.refresh_token.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a refresh token",
        "operationId": "getRefreshToken",
        "security": [
          {
            "light_oauth2": [
              "oauth.refresh_token.r",
              "oauth.refresh_token.w"
            ]
          }
        ]
      }
    },
    "/oauth2/service": {
      "post": {
        "description": "Return a service object",
        "operationId": "createService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.w"
            ]
          }
        ]
      },
      "put": {
        "description": "Return the updated service",
        "operationId": "updateService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Return all services",
        "operationId": "getAllService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.r"
            ]
          }
        ]
      }
    },
    "/oauth2/service/{serviceId}": {
      "delete": {
        "description": "Delete a service by Id",
        "operationId": "deleteService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a service by Id",
        "operationId": "getService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.r",
              "oauth.service.w"
            ]
          }
        ]
      }
    },
    "/oauth2/token": {
      "post": {
        "description": "JSON object that contains access token",
        "operationId": "postToken"
      }
    },
    "/oauth2/user": {
      "get": {
        "description": "Return all users",
        "operationId": "getAllUsers",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.r"
            ]
          }
        ]
      },
      "post": {
        "description": "Return a user object",
        "operationId": "createUser",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.w"
            ]
          }
        ]
      },
      "put": {
        "description": "Return the updated user",
        "operationId": "updateUser",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.w"
            ]
          }
        ]
      }
    },
    "/oauth2/user/{userId}": {
      "delete": {
        "description": "Delete a user by Id",
        "operationId": "deleteUser",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a user by Id",
        "operationId": "getUser",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.r",
              "oauth.user.w"
            ]
          }
        ]
      }
    },
    "/oauth2/password/{userId}": {
      "post": {
        "description": "Reset Password",
        "operationId": "resetPassword",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.w"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "light_oauth2": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "http://localhost:8888/oauth2/code",
            "scopes": {
              "oauth.client.w": "write oauth client",
              "oauth.client.r": "read oauth client",
              "oauth.key.w": "write key",
              "oauth.key.r": "read key",
              "oauth.refresh_token.w": "write oauth refresh token",
              "oauth.refresh_token.r": "read oauth refresh token",
              "oauth.service.w": "write oauth service",
              "oauth.service.r": "read oauth service",
              "oauth.user.w": "write user",
              "oauth.user.r": "read user"
            }
          }
        }
      }
    }
  }
}