---
# A light-codegen config file to generate the petstore project with Maven build
version: 3.1.0
groupId: com.networknt
artifactId: petstore
rootPackage: com.networknt.petstore
buildMaven: false
multipleModule: false
