---
rootPackage: com.networknt.todolist.command
handlerPackage: com.networknt.todolist.command.handler
modelPackage: com.networknt.todolist.command.model
artifactId: hybrid-command
groupId: com.networknt
name: hybrid-command
version: 0.1.0
overwriteHandler: true
overwriteHandlerTest: true
httpPort: 8080
enableHttp: false
httpsPort: 8443
enableHttps: true
enableHttp2: true
enableRegistry: false
supportOracle: false
supportMysql: false
supportPostgresql: false
supportH2ForTest: false
supportClient: false
dockerOrganization: networknt
