swagger: '2.0'
info:
  description: >-
    User Management service API is a microserice that used for user management
    on light-portal  built on top of light-4j framework.
  version: 1.0.0
  title: User Management service API
  contact:
    email: stevehu@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: user.networknt.com
basePath: /v1
schemes:
  - http
paths:
  /user:
    get:
      description: Return an array of user
      operationId: getAll
      security:
        - user_auth:
            - user.a
      x-accepts: application/json
      x-contentType: application/json
    post:
      description: Return a user object with Id
      operationId: addUser
      security:
        - user_auth:
            - user.w
      x-accepts: application/json
      x-contentType: application/json
  '/user/{id}':
    get:
      tags:
        - user
      summary: Find User by ID
      description: Returns a single User
      operationId: getUserById
      security:
        - user_auth:
            - user.r
    put:
      description: Return the updated user object
      operationId: updateUser
      security:
        - user_auth:
            - user.w
      x-accepts: application/json
      x-contentType: application/json
    delete:
      tags:
        - user
      summary: delete user by ID
      description: delete a single User
      operationId: deleteUserById
      security:
        - user_auth:
            - user.r
            - user.w
  /user/email:
    get:
      description: Return a user by email
      operationId: getByEmail
      security:
        - user_auth:
            - user.r
  /user/name:
    get:
      description: Return a user by user name
      operationId: getByName
      security:
        - user_auth:
            - user.r
      x-accepts: application/json
      x-contentType: application/json
  /user/login:
    put:
      description: User login process
      operationId: loginUser
      security:
        - user_auth:
            - user.r
            - user.w
      x-accepts: application/json
      x-contentType: application/json
  '/user/token/{id}':
    get:
      description: Return the  user object
      operationId: confirmUser
      security:
        - user_auth:
            - user.r
            - user.w
      x-accepts: application/json
      x-contentType: application/json
  '/session/{id}':
    get:
      description: Return a session by Id
      operationId: getBySessionId
      security:
        - session_auth:
            - session.r
      x-accepts: application/json
      x-contentType: application/json
    delete:
      description: Remove a session by Id
      operationId: deleteById
      security:
        - session_auth:
            - session.r
            - session.w
      x-accepts: application/json
      x-contentType: application/json
  /session:
    post:
      description: Return a session object with Id
      operationId: createSession
      security:
        - session_auth:
            - session.r
            - session.w
      x-accepts: application/json
      x-contentType: application/json
securityDefinitions:
  user_auth:
    type: oauth2
    authorizationUrl: 'http://localhost:8080/oauth2/code'
    flow: implicit
    scopes:
      user.r: read user
      user.w: write user
      user.a: admin user
  session_auth:
    type: oauth2
    authorizationUrl: 'http://localhost:8080/oauth2/code'
    flow: implicit
    scopes:
      session.r: read session
      session.w: write session
      session.a: admin session