---
rootPackage: net.lightapi.portal.product.query
handlerPackage: net.lightapi.portal.product.query.handler
modelPackage: net.lightapi.portal.product.query.model
artifactId: product-query
groupId: net.lightapi
name: product-query
version: 0.1.0
jsonPath: "/portal/query"
overwriteHandler: true
overwriteHandlerTest: true
httpPort: 8082
enableHttp: false
httpsPort: 8447
enableHttps: true
enableHttp2: true
enableRegistry: false
supportDb: false
supportH2ForTest: false
supportClient: false
kafkaProducer: true
kafkaConsumer: false
kafkaStreams: false
supportAvro: true
buildMaven: true
kafkaTopic: portal-event
