---
rootPackage: com.networknt.todolist.query
handlerPackage: com.networknt.todolist.query.handler
modelPackage: com.networknt.todolist.query.model
artifactId: hybrid-query
groupId: com.networknt
name: hybrid-query
version: 0.1.0
overwriteHandler: true
overwriteHandlerTest: true
httpPort: 8082
enableHttp: false
httpsPort: 8443
enableHttps: true
enableHttp2: true
enableRegistry: false
supportOracle: false
supportMysql: false
supportPostgresql: false
supportH2ForTest: false
supportClient: false
dockerOrganization: networknt
