{
  "openapi": "3.0.2",
  "info": {
    "version": "1.0.0",
    "title": "OAuth2 Services Merged into a Monolithic App",
    "description": "OAuth2 Services with all endpoints in one API.",
    "contact": {
      "email": "stevehu@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "https://oauth2.networknt.com/"
    }
  ],
  "paths": {
    "/oauth2/org": {
      "post": {
        "description": "Create an organization that is an logic instance of the OAuth 2.0 provider",
        "operationId": "createOrg",
        "security": [
          {
            "light_oauth2": [
              "oauth.org.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get all organizations",
        "operationId": "getAllOrgs",
        "security": [
          {
            "light_oauth2": [
              "oauth.org.r"
            ]
          }
        ]
      }
    },
    "/oauth2/org/{orgId}": {
      "put": {
        "description": "Update the organization orgName, orgDesc or ownerId",
        "operationId": "updateOrg",
        "security": [
          {
            "light_oauth2": [
              "oauth.org.w"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete an orgnanization by orgId",
        "operationId": "deleteOrg",
        "security": [
          {
            "light_oauth2": [
              "oauth.org.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get an organization by orgId",
        "operationId": "getOrgById",
        "security": [
          {
            "light_oauth2": [
              "oauth.org.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/client": {
      "post": {
        "description": "Create a client object under an orgId",
        "operationId": "createClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get all clients",
        "operationId": "getAllClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/client/{clientId}": {
      "put": {
        "description": "Update and client by the clientId",
        "operationId": "updateClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.w"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete a client by Id",
        "operationId": "deleteClient",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a client by Id",
        "operationId": "getClientById",
        "security": [
          {
            "light_oauth2": [
              "oauth.client.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/authorize": {
      "get": {
        "description": "Return 302 redirect with authorization code",
        "operationId": "getAuthCode"
      },
      "post": {
        "description": "Return 302 redirect with authorization code",
        "operationId": "postAuthCode"
      }
    },
    "/oauth2/{orgId}/keys": {
      "get": {
        "description": "Get jwks",
        "operationId": "getKeys",
        "security": [
          {
            "light_oauth2": [
              "oauth.key.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/refresh_token": {
      "get": {
        "description": "Return all refresh tokens",
        "operationId": "getAllRefreshToken",
        "security": [
          {
            "light_oauth2": [
              "oauth.refresh_token.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/refresh_token/{refreshToken}": {
      "delete": {
        "description": "Delete a refresh token",
        "operationId": "deleteRefreshToken",
        "security": [
          {
            "light_oauth2": [
              "oauth.refresh_token.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a refresh token",
        "operationId": "getRefreshToken",
        "security": [
          {
            "light_oauth2": [
              "oauth.refresh_token.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/service": {
      "post": {
        "description": "Create a service object",
        "operationId": "createService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get all services",
        "operationId": "getAllService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/service/{serviceId}": {
      "put": {
        "description": "update a service",
        "operationId": "updateService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.w"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete a service by Id",
        "operationId": "deleteService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a service by Id",
        "operationId": "getService",
        "security": [
          {
            "light_oauth2": [
              "oauth.service.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/token": {
      "post": {
        "description": "JSON object that contains access token",
        "operationId": "postToken"
      }
    },
    "/oauth2/{orgId}/user": {
      "get": {
        "description": "Return all users",
        "operationId": "getAllUsers",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.r"
            ]
          }
        ]
      },
      "post": {
        "description": "Create a user object",
        "operationId": "createUser",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.w"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/user/{userId}": {
      "put": {
        "description": "the update user object",
        "operationId": "updateUser",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.w"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete a user by Id",
        "operationId": "deleteUser",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.w"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a user by Id",
        "operationId": "getUser",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.r"
            ]
          }
        ]
      }
    },
    "/oauth2/{orgId}/password/{userId}": {
      "post": {
        "description": "Reset Password",
        "operationId": "resetPassword",
        "security": [
          {
            "light_oauth2": [
              "oauth.user.w"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "light_oauth2": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "http://localhost:8888/oauth2/{orgId}/authorize",
            "scopes": {
              "oauth.client.w": "write oauth client",
              "oauth.client.r": "read oauth client",
              "oauth.key.w": "write key",
              "oauth.key.r": "read key",
              "oauth.refresh_token.w": "write oauth refresh token",
              "oauth.refresh_token.r": "read oauth refresh token",
              "oauth.service.w": "write oauth service",
              "oauth.service.r": "read oauth service",
              "oauth.user.w": "write user",
              "oauth.user.r": "read user",
              "oauth.org.w": "write org",
              "oauth.org.r": "read org"
            }
          }
        }
      }
    }
  }
}