---
# A light-codegen config file to generate a single module petstore project with Maven build
version: 3.0.1
groupId: com.networknt
artifactId: petstore
rootPackage: com.networknt.petstore
supportClient: true